// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Photolabs.DAL;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(PhotolabContext))]
    partial class PhotolabContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Photolabs.Models.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 100L, null, null, null, null, null);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegularUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TopicId")
                        .HasColumnType("integer");

                    b.Property<int?>("UserAccountId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.HasIndex("UserAccountId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "Image-1-Full.jpeg",
                            RegularUrl = "Image-1-Regular.jpeg",
                            TopicId = 1,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 11,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "people-1-full.jpg",
                            RegularUrl = "people-1-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 12,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "people-2-full.jpg",
                            RegularUrl = "people-2-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 13,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "people-3-full.jpg",
                            RegularUrl = "people-3-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 14,
                            City = "Victoria",
                            Country = "Canada",
                            FullUrl = "people-4-full.jpg",
                            RegularUrl = "people-4-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 15,
                            City = "Ottawa",
                            Country = "Canada",
                            FullUrl = "people-5-full.jpg",
                            RegularUrl = "people-5-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 5
                        },
                        new
                        {
                            Id = 16,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "people-6-full.jpg",
                            RegularUrl = "people-6-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 6
                        },
                        new
                        {
                            Id = 17,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "people-7-full.jpg",
                            RegularUrl = "people-7-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 7
                        },
                        new
                        {
                            Id = 18,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "people-8-full.jpg",
                            RegularUrl = "people-8-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 8
                        },
                        new
                        {
                            Id = 19,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "people-9-full.jpg",
                            RegularUrl = "people-9-regular.jpg",
                            TopicId = 1,
                            UserAccountId = 9
                        },
                        new
                        {
                            Id = 21,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "nature-1-full.jpg",
                            RegularUrl = "nature-1-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 22,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "nature-2-full.jpg",
                            RegularUrl = "nature-2-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 23,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "nature-3-full.jpg",
                            RegularUrl = "nature-3-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 24,
                            City = "Victoria",
                            Country = "Canada",
                            FullUrl = "nature-4-full.jpg",
                            RegularUrl = "nature-4-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 25,
                            City = "Ottawa",
                            Country = "Canada",
                            FullUrl = "nature-5-full.jpg",
                            RegularUrl = "nature-5-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 5
                        },
                        new
                        {
                            Id = 26,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "nature-6-full.jpg",
                            RegularUrl = "nature-6-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 6
                        },
                        new
                        {
                            Id = 27,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "nature-7-full.jpg",
                            RegularUrl = "nature-7-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 7
                        },
                        new
                        {
                            Id = 28,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "nature-8-full.jpg",
                            RegularUrl = "nature-8-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 8
                        },
                        new
                        {
                            Id = 29,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "nature-9-full.jpg",
                            RegularUrl = "nature-9-regular.jpg",
                            TopicId = 2,
                            UserAccountId = 9
                        },
                        new
                        {
                            Id = 31,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "travel-1-full.jpg",
                            RegularUrl = "travel-1-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 32,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "travel-2-full.jpg",
                            RegularUrl = "travel-2-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 33,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "travel-3-full.jpg",
                            RegularUrl = "travel-3-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 34,
                            City = "Victoria",
                            Country = "Canada",
                            FullUrl = "travel-4-full.jpg",
                            RegularUrl = "travel-4-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 35,
                            City = "Ottawa",
                            Country = "Canada",
                            FullUrl = "travel-5-full.jpg",
                            RegularUrl = "travel-5-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 5
                        },
                        new
                        {
                            Id = 36,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "travel-6-full.jpg",
                            RegularUrl = "travel-6-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 6
                        },
                        new
                        {
                            Id = 37,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "travel-7-full.jpg",
                            RegularUrl = "travel-7-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 7
                        },
                        new
                        {
                            Id = 38,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "travel-8-full.jpg",
                            RegularUrl = "travel-8-regular.jpg",
                            TopicId = 3,
                            UserAccountId = 8
                        },
                        new
                        {
                            Id = 41,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "animals-1-full.jpg",
                            RegularUrl = "animals-1-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 42,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "animals-2-full.jpg",
                            RegularUrl = "animals-2-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 43,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "animals-3-full.jpg",
                            RegularUrl = "animals-3-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 44,
                            City = "Victoria",
                            Country = "Canada",
                            FullUrl = "animals-4-full.jpg",
                            RegularUrl = "animals-4-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 45,
                            City = "Ottawa",
                            Country = "Canada",
                            FullUrl = "animals-5-full.jpg",
                            RegularUrl = "animals-5-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 5
                        },
                        new
                        {
                            Id = 46,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "animals-6-full.jpg",
                            RegularUrl = "animals-6-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 6
                        },
                        new
                        {
                            Id = 47,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "animals-7-full.jpg",
                            RegularUrl = "animals-7-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 7
                        },
                        new
                        {
                            Id = 48,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "animals-8-full.jpg",
                            RegularUrl = "animals-8-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 8
                        },
                        new
                        {
                            Id = 49,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "animals-9-full.jpg",
                            RegularUrl = "animals-9-regular.jpg",
                            TopicId = 4,
                            UserAccountId = 9
                        },
                        new
                        {
                            Id = 51,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "fashion-1-full.jpg",
                            RegularUrl = "fashion-1-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 1
                        },
                        new
                        {
                            Id = 52,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "fashion-2-full.jpg",
                            RegularUrl = "fashion-2-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 2
                        },
                        new
                        {
                            Id = 53,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "fashion-3-full.jpg",
                            RegularUrl = "fashion-3-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 3
                        },
                        new
                        {
                            Id = 54,
                            City = "Victoria",
                            Country = "Canada",
                            FullUrl = "fashion-4-full.jpg",
                            RegularUrl = "fashion-4-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 4
                        },
                        new
                        {
                            Id = 55,
                            City = "Ottawa",
                            Country = "Canada",
                            FullUrl = "fashion-5-full.jpg",
                            RegularUrl = "fashion-5-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 5
                        },
                        new
                        {
                            Id = 56,
                            City = "Montreal",
                            Country = "Canada",
                            FullUrl = "fashion-6-full.jpg",
                            RegularUrl = "fashion-6-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 6
                        },
                        new
                        {
                            Id = 57,
                            City = "Toronto",
                            Country = "Canada",
                            FullUrl = "fashion-7-full.jpg",
                            RegularUrl = "fashion-7-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 7
                        },
                        new
                        {
                            Id = 58,
                            City = "Vancouver",
                            Country = "Canada",
                            FullUrl = "fashion-8-full.jpg",
                            RegularUrl = "fashion-8-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 8
                        },
                        new
                        {
                            Id = 59,
                            City = "Calgary",
                            Country = "Canada",
                            FullUrl = "fashion-9-full.jpg",
                            RegularUrl = "fashion-9-regular.jpg",
                            TopicId = 5,
                            UserAccountId = 9
                        });
                });

            modelBuilder.Entity("Photolabs.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 100L, null, null, null, null, null);

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Slug = "people",
                            Title = "People"
                        },
                        new
                        {
                            Id = 2,
                            Slug = "nature",
                            Title = "Nature"
                        },
                        new
                        {
                            Id = 3,
                            Slug = "travel",
                            Title = "Travel"
                        },
                        new
                        {
                            Id = 4,
                            Slug = "animals",
                            Title = "Animals"
                        },
                        new
                        {
                            Id = 5,
                            Slug = "fashion",
                            Title = "Fashion"
                        });
                });

            modelBuilder.Entity("Photolabs.Models.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 100L, null, null, null, null, null);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "John Doe",
                            ProfileUrl = "profile-1.jpg",
                            Username = "jdoe"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Alice Wonderland",
                            ProfileUrl = "profile-2.jpg",
                            Username = "awond"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sita Dennis",
                            ProfileUrl = "profile-3.jpg",
                            Username = "sitad"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Sasha Mateo",
                            ProfileUrl = "profile-4.jpg",
                            Username = "matte"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Anita Austi",
                            ProfileUrl = "profile-5.jpg",
                            Username = "anita"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Lukas Souza",
                            ProfileUrl = "profile-6.jpg",
                            Username = "lsouza"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Jose Alejandro",
                            ProfileUrl = "profile-7.jpg",
                            Username = "josea"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Dwayne Jacob",
                            ProfileUrl = "profile-8.jpg",
                            Username = "jdwayne"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Allison Saeng",
                            ProfileUrl = "profile-9.jpg",
                            Username = "saeng"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Adrea Santos",
                            ProfileUrl = "profile-10.jpg",
                            Username = "santa"
                        });
                });

            modelBuilder.Entity("Photolabs.Models.Photo", b =>
                {
                    b.HasOne("Photolabs.Models.Topic", null)
                        .WithMany("Photos")
                        .HasForeignKey("TopicId");

                    b.HasOne("Photolabs.Models.UserAccount", null)
                        .WithMany("Photos")
                        .HasForeignKey("UserAccountId");
                });

            modelBuilder.Entity("Photolabs.Models.Topic", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Photolabs.Models.UserAccount", b =>
                {
                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
